### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1
### Verbo GET – listar um
GET http://localhost:8000/funcionario/10 HTTP/1.1
### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
content-type: application/json

{
    "nome" : "Vinicius de Liz da Conceição",
    "matricula": "vi12345",
    "cpf" : "3",
    "telefone" : "te233849212",
    "grupo" : 3,
    "senha" : "qualqueruma123"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/2 HTTP/1.1
content-type: application/json

{
    "senha" : "novasenha123"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/3 HTTP/1.1

# Vinicius de Liz da Conceição