// Fazer os testes que só falta isso

### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1
### Verbo GET – listar um
GET http://localhost:8000/produto/10 HTTP/1.1
### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json

{
    "nome": "Pastel com queijo",
    "descricao": "Pastel com queijo bem delicioso",
    "foto": "foto.png",
    "valor_unitario": 5.50
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1
content-type: application/json

{
    "nome": "Pastel com queijo",
    "descricao": "Pastel com queijo bem delicioso",
    "foto": "foto.png",
    "valor_unitario": 5.50
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/3 HTTP/1.1

# Vinicius de Liz da Conceição