### token gerado
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWQiOjgsImdydXBvIjoxLCJleHAiOjE3NzUyNDIyNzIsInR5cGUiOiJhY2Nlc3MifQ.-K89NYksf2aMzhaWwpbKCHjMyqixZI29yyjLPF-U02o
# @refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWQiOjgsImdydXBvIjoxLCJleHAiOjE3NzU4NDUxODMsInR5cGUiOiJyZWZyZXNoIn0.348OnhJE-bAVqC1RAuMGPdfpdKeVpbyYKhjl3n62dKE


### Minhas logs não está salvando parei no slide 28 e 29, revisar tudo até arrumar as logs


### Listar ações e recursos já utilizados e disponíveis para filtro
GET http://127.0.0.1:8000/auditoria/acoes
Authorization: Bearer {{access_token}}

### Listar auditoria geral
GET http://127.0.0.1:8000/auditoria
Authorization: Bearer {{access_token}}

### Listar auditoria com múltiplos filtros e paginação
GET http://127.0.0.1:8000/auditoria?funcionario_id=1&acao=LOGIN,CREATE&recurso=auth,comanda&data_inicio=2024-01-01&data_fim=2024=12=31&skip=0&limite=50
Authorization: Bearer {{access_token}}

### Paginação = segunda página
GET http://127.0.0.1:8000/auditoria?skip=50&limite=50
Authorization: Bearer {{access_token}}

### Terminei slide 21